# Generated by Django 4.2.5 on 2023-09-27 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('type', models.CharField(choices=[('back', 'back-end'),
                                                   ('front', 'front-end'),
                                                   ('iOS', 'iOS'),
                                                   ('Android', 'Android')],
                                          max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='project_author',
                                             related_query_name='project_author',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('tag', models.CharField(choices=[('bug', 'BUG'),
                                                  ('feature', 'FEATURE'),
                                                  ('task', 'TASK')],
                                         max_length=128)),
                ('priority', models.CharField(choices=[('low', 'LOW'),
                                                       ('medium', 'MEDIUM'),
                                                       ('high', 'HIGH')],
                                              max_length=128)),
                ('statut', models.CharField(choices=[('to_do', 'To Do'),
                                                     ('in_progress', ' In Progress'),
                                                     ('finished', 'Finished')],
                                            default='to_do', max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='issue_author',
                                             related_query_name='issue_author',
                                             to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='issue_project',
                                              related_query_name='issue_project',
                                              to='projet.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=2048)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='comment_author',
                                             related_query_name='comment_author',
                                             to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='comment_issue',
                                            related_query_name='comment_issue',
                                            to='projet.issue')),
            ],
        ),
    ]
