# Generated by Django 4.2.5 on 2023-12-26 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0003_alter_comment_author_alter_issue_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', related_query_name='issue_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
